services:
  datahub:
    container_name: microbiome-datahub
    image: node:18
    volumes:
      - ./microbiome-datahub:/microbiome-datahub
    command: bin/sh -c "cd /microbiome-datahub && npm ci && npm run build"
  web:
    container_name: microbiome-web
    image: nginx:1.24.0
    ports:
      - "8080:80"
    volumes:
      - ./microbiome-datahub/dist:/usr/share/nginx/html:ro